if(WIN32)
    set(PLATFORM_NAME "Windows")
    set(LIB_SUFFIX ".lib")
    set(SHARED_LIB_SUFFIX ".dll")
    #add_definitions(-D_WIN32)
elseif(APPLE)
    set(PLATFORM_NAME "macOS")
    set(LIB_SUFFIX ".a")
    set(SHARED_LIB_SUFFIX ".dylib")
    #add_definitions(-D__APPLE__)
elseif(UNIX)
    set(PLATFORM_NAME "Linux")
    set(LIB_SUFFIX ".a")
    set(SHARED_LIB_SUFFIX ".so")
    #add_definitions(-D__linux__)
endif()

if(CMAKE_CXX_COMPILER_ID MATCHES "MSVC")
    message(STATUS "Compiler: MSVC")
    set(COMPILER_MSVC TRUE)
    set(COMPILER_MSVC_LIKE TRUE)
elseif(CMAKE_C_COMPILER_ID MATCHES "MSVC")
    message(STATUS "Compiler: MSVC (detected via C)")
    set(COMPILER_MSVC TRUE)
    set(COMPILER_MSVC_LIKE TRUE)
elseif(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
    if(CMAKE_CXX_SIMULATE_ID STREQUAL "MSVC")
        message(STATUS "Compiler: Clang-Cl (MSVC-compatible)")
        set(COMPILER_CLANG_CL TRUE)
        set(COMPILER_MSVC_LIKE TRUE)
    else()
        message(STATUS "Compiler: Clang")
        set(COMPILER_CLANG TRUE)
        set(COMPILER_MSVC_LIKE FALSE)
    endif()
elseif(CMAKE_C_COMPILER_ID MATCHES "Clang")
    if(CMAKE_C_SIMULATE_ID STREQUAL "MSVC")
        message(STATUS "Compiler: Clang-Cl (MSVC-compatible, detected via C)")
        set(COMPILER_CLANG_CL TRUE)
        set(COMPILER_MSVC_LIKE TRUE)
    else()
        message(STATUS "Compiler: Clang (detected via C)")
        set(COMPILER_CLANG TRUE)
        set(COMPILER_MSVC_LIKE FALSE)
    endif()
elseif(CMAKE_CXX_COMPILER_ID MATCHES "GNU")
    message(STATUS "Compiler: GCC")
    set(COMPILER_GCC TRUE)
    set(COMPILER_MSVC_LIKE FALSE)
elseif(CMAKE_C_COMPILER_ID MATCHES "GNU")
    message(STATUS "Compiler: GCC (detected via C)")
    set(COMPILER_GCC TRUE)
    set(COMPILER_MSVC_LIKE FALSE)
else()
    message(WARNING "Unknown compiler: CXX=${CMAKE_CXX_COMPILER_ID} C=${CMAKE_C_COMPILER_ID}")
    set(COMPILER_MSVC_LIKE FALSE)
endif()

if(CMAKE_SYSTEM_PROCESSOR MATCHES "(x86_64|AMD64|amd64)")
    set(ARCH "x64")
    set(ARCH_DEFINE "_M_X64")
elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "(i386|i686|x86)")
    set(ARCH "x86")
    set(ARCH_DEFINE "_M_IX86")
elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "(arm64|aarch64)")
    set(ARCH "arm64")
    set(ARCH_DEFINE "_M_ARM64")
elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "(arm|armv7|armv7l)")
    set(ARCH "arm")
    set(ARCH_DEFINE "_M_ARM")
else()
    message(WARNING "Unknown CPU architecture: ${CMAKE_SYSTEM_PROCESSOR}, falling back to pointer size")
    if(CMAKE_SIZEOF_VOID_P EQUAL 8)
        set(ARCH "x64")
        set(ARCH_DEFINE "_M_X64")
    else()
        set(ARCH "x86")
        set(ARCH_DEFINE "_M_IX86")
    endif()
endif()

set(PLATFORM_SUFFIX "${ARCH}")

##add_definitions(-D${ARCH_DEFINE})

#if(ARCH STREQUAL "arm64" OR ARCH STREQUAL "arm")
#    add_definitions(-D__ARM_ARCH)
#endif()

if(CMAKE_SIZEOF_VOID_P EQUAL 8)
    set(CMAKE_64BIT TRUE)
else()
    set(CMAKE_32BIT TRUE)
endif()

# Some package exports only provide Debug/Release artifacts.
# Keep RelWithDebInfo and MinSizeRel mapped to Release reliably.
if(NOT CMAKE_MAP_IMPORTED_CONFIG_RELWITHDEBINFO)
    set(CMAKE_MAP_IMPORTED_CONFIG_RELWITHDEBINFO "Release")
endif()
if(NOT CMAKE_MAP_IMPORTED_CONFIG_MINSIZEREL)
    set(CMAKE_MAP_IMPORTED_CONFIG_MINSIZEREL "Release")
endif()

set(CMAKE_CONFIGURATION_TYPES "Debug;Release;RelWithDebInfo;MinSizeRel" CACHE STRING "" FORCE)
if(NOT CMAKE_BUILD_TYPE AND NOT CMAKE_CONFIGURATION_TYPES)
    set(CMAKE_BUILD_TYPE "Debug" CACHE STRING "Choose the type of build" FORCE)
    set_property(CACHE CMAKE_BUILD_TYPE PROPERTY STRINGS "Debug" "Release" "RelWithDebInfo" "MinSizeRel")
endif()

# /ZI Support editing and continue, only x64 or x86, ARM not supported
# Note: The /ZI option is also incompatible with the use of the __LINE__ predefined macro
#if(MSVC)
#    string(REPLACE "/Zi" "/ZI" CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG}")
#endif()